### ISSUE TITLE
BUG: getParam in onCreated returns null

### ISSUE THREAD

**Issue by smeijer** [meteorhacks/flow-router#95]
Doesn't feel right that `FlowRouter.getParam` returns something different then `FlowRouter.current().params`

```js
// url: /t/abc123
// route '/t/:token?'

Template.myContent.onCreated(function() {
  var token1 = FlowRouter.getParam('token'); // returns null
  var token2 = FlowRouter.current().params.token; // returns abc123
});
```

**Comment by richsilv** [comment]
+1 - I have exactly the same situation.

**Comment by fvpDev** [comment]
+1 - Same thing here

**Comment by elidoran** [comment]
I believe this is caused [here](https://github.com/meteorhacks/flow-router/blob/master/client/router.js#L301) when the action is called before registering the reactive values for [params](https://github.com/meteorhacks/flow-router/blob/master/client/router.js#L305) and [query params](https://github.com/meteorhacks/flow-router/blob/master/client/router.js#L306).

So, what happens is:

1. in line 301 the action is called
2. in the action `FlowLayout.render()` is called
3. the render triggers your `Template.onCreated()` function
4. then `FlowRouter.getParam()` returns null
5. the action returns
6. in line 305 `self._registerParams()` is called which sets the reactive params

@arunoda What do you think? Should lines 305 and 306 go before line 301's `Tracker.nonreactive()` call?

**Comment by arunoda** [comment]
I get your point and that's the reason for this issue.

But if we implement that, old route's template will get re-rendered another time with the new routes data. That might be okay for some template which stays forever. It cause trouble for templates which is going to destroy. I didn't check this. (May be this won't be an issue since they'll get removed anyway)

If we can do a test and see it don't make any issue, we are good to go.

**Comment by elidoran** [comment]
Great point. It would trigger Trackers in current Templates and there's bound to be some about to be destroyed. When I looked earlier I saw line 308 `self._currentTracker.changed();` and was thinking they wouldn't be notified yet. Woops. Different tracker.

**FlowLayout Option**

When using both FlowRouter and FlowLayout a solution would somehow split FlowLayout's render into two phases: 1. destroying the templates which aren't needed anymore, and, 2. creating the new templates. With FlowRouter somehow knowing phase 1 has been done so it can set the new ReactiveDict values before phase 2 runs. Both FlowRouter and FlowLayout are your packages. Would you be interested in FlowRouter listening for FlowLayout's render phases? Or at least for phase 1. It's essentially adding a listener which calls the self._register* functions when FlowLayout finishes its destroy phase. If they haven't been called after the action has been called then FlowRouter can call them like it does now.

This would also only solve this problem for those using FlowLayout and having trouble with `Template.onCreated`. Other `action` types could encounter similar trouble.

**New Function: FlowRouter#ensureReactive()**

What about adding a function to tell FlowRouter to ensure it has updated the reactive values for the current route? Like `FlowRouter.ensureReactive()` which tells FlowRouter to update its reactive values for the current route if it hasn't done so? It wouldn't break the current API and it would allow the above example to do this:

```javascript
// url: /t/abc123
// route '/t/:token?'
Template.myContent.onCreated(function() {
  FlowRouter.ensureReactive();
  var token1 = FlowRouter.getParam('token'); // returns abc123
  var token2 = FlowRouter.current().params.token; // returns abc123
});
```

This requires dev's encountering this issue to tell FlowRouter to ensure the update has been done for the current route. We'd have to track whether the update for the current route was done so we don't do it a second time after the action is called or when the Tracker computation is rerun.

**Passing a boolean**

Or, add a boolean as a second param to the current API functions which tells FlowRouter to ensure the reactive values are updated: `FlowRouter.getParam('token', true);`


Only the first option would handle it automatically without developers doing something in their code.

Thoughts anyone?

**Comment by arunoda** [comment]
I believe we can solve this and the other reactive issues, if we dive into the problem a bit. 

I still we could deal with this without the intervention of the user.

**Comment by rclai** [comment]
What great timing! I hope you get this resolved, this would be a bummer.

I was just this out in [this MeteorPad](http://meteorpad.com/pad/smy3ano7Tk9nsBhu4/FlowLayout%20+%20FlowRouter%20and%20Blaze%20Components). The `staticToken` is not printing.

**Comment by arunoda** [comment]
Yes it is. This is my top priority for flow router. Let's see.

**Comment by delgermurun** [comment]
> But if we implement that, old route's template will get re-rendered another time with the new routes data. That might be okay for some template which stays forever. It cause trouble for templates which is going to destroy. I didn't check this. (May be this won't be an issue since they'll get removed anyway)

@arunoda @elidoran can you guys post code snippet that produce this side effect?

I tried below code:
```js
Template.myContent.helpers({
  token: function() {
    console.log('getting token');
    return FlowRouter.getParam('token');
  }
});
```

on template `{{token}}`.

If we render different layout (ofc using `flow-layout`) `token` helper doesn't rerun. If we render same layout with different template `token` helper rerun just before destroy it's template.

But this issue doesn't depend on #107 PR, `token` helper rerun anyway.

**Comment by arunoda** [comment]
I started working on this on `fix-reactive-bugs` branch. It have a fix for #103 but not for this.

My idea is to isolate the reactiveData for each route definition. Then we can deal with this issue. 
We may have some side effects because of that, but anyway let's give it a try.

**Comment by arunoda** [comment]
Guys, can you now check the `fix-reactive-bugs` branch. I've a proper fix on that.

**Comment by elidoran** [comment]
This issue seems fixed by `fix-reactive-bugs` branch.

**Comment by arunoda** [comment]
Nice to hear that.

**Comment by arunoda** [comment]
Released version `1.8.0` with fixes for this bug.

**Comment by rclai** [comment]
I think this is still an issue. Let me see if I can reproduce.

**Comment by richsilv** [comment]
Sorry to bother you, @arunoda but I still have exactly this problem with v1.10.0.

```
FlowRouter.route('/genre/:genre', {
  name: 'appMarketGenre',
  action: function(params, queryParams) {
    FlowLayout.render('MasterLayout', {mainSection: 'Genre'});
  }
});
```

```
Template.Genre.onCreated(function() {
  console.log(FlowRouter.getParam('genre'), FlowRouter.current().params.genre);
});
```

yields:

    undefined "publishing"

when you navigate to `/genre/publishing` and so on.

**Comment by arunoda** [comment]
Okay

**Comment by arunoda** [comment]
@richsilv I tried with as your code but it works well for me. 
repo: https://github.com/arunoda/flow-oncreated-issue
video: http://recordit.co/Hi9B75Xh8b

Can you play with this app? or try to send me a the usecase you've

**Comment by richsilv** [comment]
Profuse apologies - I was running this on a dev branch that was still using v1.7.1...

**Comment by arunoda** [comment]
okay. closing then.
